# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abb038c6b345b1bfeebb1e850ffe39520e786230421a8eab7cf767b0ca60c14f755cd7409e32a98305019771f1d0a56a4b23198b4b2bb875d0127713ec27fa71

test:
  secret_key_base: 4184c20414f1ad6118693d31d845d82f1eada84922de2b738edc2b98ab953d7c1fedf805eb0bae71a9dedb0e8159066ed84e1bfdc90ef3c8c1baf8c5a249bb1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
